config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  resources :reservations # controller: "reservations"
  get '/reservations/confirm/:id' => 'reservation#confirm_reservation'

  resources :listings 
  get '/listing/:id' => 'listing#show'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:show, :edit, :update, :destroy]
  
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  resources :articles
 
  root 'welcome#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

    

end

app/models/listing.rb
class Listing < ActiveRecord::Base

	validates :avatars, presence: true

	belongs_to :user
	has_many :listing_tags
	has_many :tags, through: :listing_tags
	has_many :reservations, :dependent => :destroy

	mount_uploaders :avatars, AvatarUploader

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  before_action :find_listing, only: [:show, :edit, :destroy, :update]

  def index
  	@listings = Listing.all # index function
  end

  def show
    @reservation = Reservation.new
  end

  def new
  	@listing = Listing.new
  end	

  def create
    
    @listing = current_user.listings.new(listing_params)
    if @listing.save
       redirect_to root_url
    else 
      render :new
    end 
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      flash[:success] = 'You have updated your listing successfully!'
       redirect_to listing_path(@listing)
    else 
      render :edit
    end
  end

  def destroy
    @listing.destroy
    redirect_to root_path
	end

  def find_listing
    @listing = Listing.find(params[:id]) 
  end 

  private
  def listing_params
    params.require(:listing).permit(:name, :description, :address, :country, :city, :price, :user_id, :accomodates, {avatars:[]}, :property_type, {:tag_ids=>[]}, :bedrooms, :bathrooms )
  end 

end



# get '/listing/:id' do
# 	erb :"listings/index.html.erb"
# end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for @listing do |f| %>
	<p id="new_listing_name">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>

	<p id="new_listing_description">
		<%= f.label :description %>
		<%= f.text_field :description %>
	</p>

	<p id="new_listing_address">
		<%= f.label :address %>
		<%= f.text_field :address %>
	</p>

	<p id="new_listing_country">
		<%= f.label :country %>
		<%= f.text_field :country %>
	</p>

	<p id="new_listing_city">
		<%= f.label :city %>
		<%= f.text_field :city %>
	</p>

	<p id="new_listing_property_type">
		<%= f.label :property_type %>
		<%= f.select :property_type, [['Apartment','Apartment'],['House','House'],['Condominium','Condominium']] %>
	</p>

	<p id="new_listing_accomodates">
		<%= f.label :accomodates %>
		<%= f.number_field :accomodates %>
	</p>

	<p id="new_listing_bedrooms">
		<%= f.label :bedrooms %>
		<%= f.number_field :bedrooms %>
	</p>

		<p id="new_listing_bathrooms">
		<%= f.label :bathrooms %>
		<%= f.number_field :bathrooms %>
	</p>

	<p id="new_listing_price">
		<%= f.label :price %>
		<%= f.number_field :price %>
	</p>

	<p><%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) %></p>

	<%= f.file_field :avatars, multiple: true %>


	<p id="new_listing_submit_button">
		<%= f.submit %>
	</p>



<%end%> 

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>
<%= render partial: 'form' %>

app/views/listings/index.html.erb
<h1>Listings#index</h1>
<p>Find me in app/views/listings/index.html.erb</p>

app/views/listings/new.html.erb
<%= form_for @listing do |f| %>
	<p id="new_listing_">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>

	<p id="new_listing_">
		<%= f.label :description %>
		<%= f.text_field :description %>
	</p>

	<p id="new_listing_">
		<%= f.label :address %>
		<%= f.text_field :address %>
	</p>

	<p id="new_listing_">
		<%= f.label :country %>
		<%= f.text_field :country %>
	</p>

	<p id="new_listing_">
		<%= f.label :city %>
		<%= f.text_field :city %>
	</p>

	<p id="new_listing_">
		<%= f.label :price %>
		<%= f.number_field :price %>
	</p>
	<p id="new_listing_">
		<%= f.submit %>
	</p>

<%end%> 

app/views/listings/show.html.erb
<%= image_tag (@listing.avatars[0].large.url) %>



<p><%= form_for @reservation do |f| %></p>
<p> Check in / check out dates </p>
<div class="container">
    <div class='col-md-5'>
        <div class="form-group">
            <div class='input-group date' id='datetimepicker6'>
                <%= f.text_field :start_date %>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>
    <div class='col-md-5'>
        <div class="form-group">
            <div class='input-group date' id='datetimepicker7'>
                <%= f.text_field :end_date %>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>
</div>



<%= f.hidden_field :total_price, :value => @listing.price  %>
<%= f.hidden_field :listing_id, :value => @listing.id %> 

<%= f.submit "book now!" %>

<% end %>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker6').datetimepicker({format: 'DD/MM/YYYY'});
        $('#datetimepicker7').datetimepicker({format: 'DD/MM/YYYY',
            useCurrent: false //Important! See issue #1075
        });
        $("#datetimepicker6").on("dp.change", function (e) {
            $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
        });
        $("#datetimepicker7").on("dp.change", function (e) {
            $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
        });
    });
</script>





<ul> 
	<li> <%= @listing.name %> </li>
	<li> <%= @listing.description %> </li>
	<li> <%= @listing.property_type %> </li>
	<li> <%= @listing.address %> </li>
	<li> <%= @listing.city %> </li>
	<li> <%= @listing.country %> </li>
	<li> Accomodates <%= @listing.accomodates %> </li>
	<li> <%= @listing.bedrooms %> Bedrooms</li>
	<li> <%= @listing.bathrooms %> Bathrooms</li>
	<li> <%= @listing.price %> Ringits per night </li>
</ul>
	<p> Features: </p>
	<% @listing.tags.each do |tag|%>
		<p><%=tag.name%></p>
	<%end %>



<% if @listing.user_id == current_user.id %>
		<p><%= link_to 'Remove this listing', listing_path(@listing), method: :delete %></p>
		<p><%= link_to 'Edit this listing', edit_listing_path(@listing) %></p>
        <br>
<% end %>