config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  resources :reservations # controller: "reservations"
  get '/reservations/confirm/:id' => 'reservation#confirm_reservation'

  resources :listings 
  get '/listing/:id' => 'listing#show'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:show, :edit, :update, :destroy]
  
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  resources :articles
 
  root 'welcome#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

    

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  
    listings_per_page = 2
    params[:page] = 1 unless params[:page]
    first_listing = (params[:page].to_i - 1 ) * listings_per_page
    listings = Listing.all
    @total_pages = listings.count / listings_per_page
    if listings.count % listings_per_page > 0
      @total_pages += 1
    end
      @listings = listings[first_listing...(first_listing + listings_per_page)]


  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container"> 


	<div class="content">



		<div class="nav">
			<ul class="links">
				<li id="search"> Search </li>
				<a href = /listings/new id="new_listing"> List property </a>
		</div>


		<div class="main">


			<h2> all listings </h2>
				<% @listings.each do |l| %>
				<%= image_tag (l.avatars[0].medium.url) %>
				<%= link_to l.name, listing_path(l) %>				<br>

				<br>	


					<% end %>
			</div>



		</div>


	</div>

</div>

<div>
	<% (1..@total_pages).each do |page| %>
	<%= link_to page, controller: "welcome", action: "index", page: page %>&nbsp;
	<% end %>
</div>