config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  resources :reservations # controller: "reservations"
  get '/reservations/confirm/:id' => 'reservation#confirm_reservation'

  resources :listings 
  get '/listing/:id' => 'listing#show'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:show, :edit, :update, :destroy]
  
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  resources :articles
 
  root 'welcome#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

    

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base

 belongs_to :user

  def self.create_with_omniauth(auth_hash)
    create! do |auth|
      auth.provider = auth_hash["provider"]
      auth.uid = auth_hash["uid"]
      auth.token = auth_hash["credentials"]["token"]
    end
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end

end

app/models/listing.rb
class Listing < ActiveRecord::Base

	validates :avatars, presence: true

	belongs_to :user
	has_many :listing_tags
	has_many :tags, through: :listing_tags
	has_many :reservations, :dependent => :destroy

	mount_uploaders :avatars, AvatarUploader

end

app/models/listing_tag.rb
class ListingTag < ActiveRecord::Base

belongs_to :tag
belongs_to :listing


end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

belongs_to :user
belongs_to :listing

end

app/models/tag.rb
class Tag < ActiveRecord::Base

has_many :listing_tags, :dependent => :destroy

end

app/models/user.rb
class User < ActiveRecord::Base

  include Clearance::User


  has_many :authentications, :dependent => :destroy
  has_many :listings, :dependent => :destroy
  has_many :reservations, :dependent => :destroy

	def self.create_with_auth_and_hash(authentication,auth_hash)
		byebug
	  create! do |u|
	    u.first_name = auth_hash["info"]["first_name"]
	    u.email = auth_hash["extra"]["raw_info"]["email"]
	    # u.encrypted_password = SecureRandom.hex(6)
	    u.authentications<<(authentication)
	  end
	end

	def fb_token
	  x = self.authentications.where(:provider => :facebook).first
	  return x.token unless x.nil?
	end

	def password_optional?
	  true
	end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login

   def index
    current_user.articles
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def new

	end

	def create
		
	  @article = Article.new(article_params)
	 
	  @article.save
	  redirect_to @article
	end

	def show


	end 

	private
  def article_params
    params.require(:article).permit(:title, :text)
  end


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  before_action :find_listing, only: [:show, :edit, :destroy, :update]

  def index
  	@listings = Listing.all # index function
  end

  def show
    @reservation = Reservation.new
  end

  def new
  	@listing = Listing.new
  end	

  def create
    
    @listing = current_user.listings.new(listing_params)
    if @listing.save
       redirect_to root_url
    else 
      render :new
    end 
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      flash[:success] = 'You have updated your listing successfully!'
       redirect_to listing_path(@listing)
    else 
      render :edit
    end
  end

  def destroy
    @listing.destroy
    redirect_to root_path
	end

  def find_listing
    @listing = Listing.find(params[:id]) 
  end 

  private
  def listing_params
    params.require(:listing).permit(:name, :description, :address, :country, :city, :price, :user_id, :accomodates, {avatars:[]}, :property_type, {:tag_ids=>[]}, :bedrooms, :bathrooms )
  end 

end



# get '/listing/:id' do
# 	erb :"listings/index.html.erb"
# end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController

  def create_from_omniauth
    auth_hash = request.env["omniauth.auth"]
byebug
    authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
    if authentication.user
      user = authentication.user 
      authentication.update_token(auth_hash)
      @next = root_url
      @notice = "Signed in!"
    else
      user = User.create_with_auth_and_hash(authentication,auth_hash)
      @next = edit_user_path(user)   
      @notice = "User created - confirm or edit details..."
    end
    sign_in(user)
    redirect_to @next, :notice => @notice
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

	# def create
	# 	@user = user_from_params


	# # respond_to do |format|
 # #    if @user.save

 # #      # Sends email to user when user is created.
 # #      ReservationMailer.confirmation_email(@user).deliver

 # #      format.html { redirect_to @user, notice: 'User was successfully created.' }
 # #      format.json { render :show, status: :created, location: @user }
 # #    else
 # #      format.html { render :new }
 # #      format.json { render json: @user.errors, status: :unprocessable_entity }
 #   end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  
    listings_per_page = 2
    params[:page] = 1 unless params[:page]
    first_listing = (params[:page].to_i - 1 ) * listings_per_page
    listings = Listing.all
    @total_pages = listings.count / listings_per_page
    if listings.count % listings_per_page > 0
      @total_pages += 1
    end
      @listings = listings[first_listing...(first_listing + listings_per_page)]


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/listing_tags_helper.rb
module ListingTagsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirBnbClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body>





<nav class="menu">
  <ul class="active">
    <li class="current-item"><%= link_to "Home", root_url %></li>
    <li><%= link_to "Signup", "#" %></li>
    <li>
          <% if signed_in? %>
        <%= link_to 'Logout', sign_out_path, method: :delete %> 
      
      <% else %>
        
          <a href="#" data-toggle="modal" data-target="#login-modal">Login</a>

          <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
          <div class="modal-dialog">
          <div class="loginmodal-container">
          <h1>Login to Your Account</h1><br>


<!--           <form>
          <input type="text" name="user" placeholder="Username">
          
          <input type="submit" name="login" class="login loginmodal-submit" value="Login">
          </form> -->

          
          <div id="clearance" class="sign-in">
          <h2><%= t(".title") %></h2>
          <%= form_for :session, url: session_path do |form| %>
          <div class="text-field">
            <%= form.label :email %>
            <%= form.text_field :email, type: 'email' %>
          </div>


          <div class="password-field" name="pass" placeholder="Password">
          <!-- <input type="password" > -->
            <%= form.label :password %>
            <%= form.password_field :password %>
          </div>


          <div class="submit-field">
          <%= form.submit  %>
          </div>

          <div class="other-links">
          <% if Clearance.configuration.allow_sign_up? %>
      
            <%= link_to t(".sign_up"), sign_up_path %>
          <% end %>
          <%= link_to t(".forgot_password"), new_password_path %>
          <div class="fb-login-button" data-max-rows="1" data-size="small" data-show-faces="false" data-auto-logout-link="false"></div>
      
      </div>
    <% end %>
</div>

      <!--     <div class="login-help">000000000
          <a href="#">Register</a> - <a href="#">Forgot Password</a>
          </div> -->
        </div>
      </div>
      </div>



      <% end %>
    </li>
    <li><%= link_to "About Us", "#" %></li>
    
  </ul>
</nav>


    



<!-- <a href= 'auth/facebook'>Login in to facebook</a> -->

  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.7&appId=189803801446399";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>


  <%= yield %>

      

      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>


  </body>

</div>